# DDP
gpus: "0,1"
flag: train

# Log
log_dir: "./log/bisai1"

# Task
if_predict_label: true
if_predict_mask: false

# Model
model:
  name: BisaiBaseline

# Train dataset
train_dataset:
  name: BisaiDataset
  dataset_name: train
  init_config:
    image_size: 512
    path: /kaggle/input/foren-tmp-data/_output_/train.csv
    root_dir: /kaggle/input/foren-tmp-data/_output_/training_data
#  Test dataset (one or many)
test_dataset:
  - name: AIGCLabelDataset
    dataset_name: zhanwei
    init_config:
      image_size: 224
      path: /kaggle/working/ForensicHub/ForensicHub/tasks/null.json

# Transform
transform:
  name: BisaiTransform
  init_config:
    norm_type: image_net

# Evaluators
evaluator:
  - name: ImageF1
    init_config:
      threshold: 0.5

# Training related
batch_size: 8
test_batch_size: 64
epochs: 100
accum_iter: 1
record_epoch: 20  # Save the best only after record epoch.

# Test related
no_model_eval: false
test_period: 1000

# Logging & TensorBoard
log_per_epoch_count: 20

# DDP & AMP settings
find_unused_parameters: true
use_amp: true

# Optimizer parameters
weight_decay: 0.05
lr: 1e-4
blr: 0.001
min_lr: 1e-5
warmup_epochs: 1

# Device and training control
device: "cuda"
seed: 42
resume: ""
start_epoch: 0
num_workers: 12
pin_mem: true

# Distributed training parameters
world_size: 1
local_rank: -1
dist_on_itp: false
dist_url: "env://"

